### ISSUE TITLE
Both Spider Textures are invisible

### ISSUE THREAD

**Issue by sebasteven** [ClassicFaithful/Classic-32x-Bedrock#2]
The spider and the cave spider is invisible due to the texture being black except their eyes which show up properly.

https://imgur.com/gallery/DrUR2WW
https://imgur.com/a/q8WTSC2

**Comment by 3vorp** [comment]
should be fixed, the texture file was improperly formatted because bedrock does it weirdly, please try it again and let me know if it's still broken
